# Generated by Django 4.1.1 on 2022-09-19 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('identificacion', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(max_length=2)),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(max_length=2)),
                ('email', models.EmailField(max_length=45, unique=True)),
                ('telefono', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=45)),
                ('ciudad', models.CharField(max_length=45)),
                ('fecha_registro', models.DateField()),
                ('password', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('codigo_rol', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('activo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Auxiliar',
            fields=[
                ('cargo', models.CharField(max_length=45)),
                ('fecha_contrato', models.DateField()),
                ('identificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='authApp.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Enfermera',
            fields=[
                ('identificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='authApp.persona')),
                ('area', models.CharField(max_length=30)),
                ('anio_contrato', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('parentesco', models.CharField(max_length=45)),
                ('identificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='authApp.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('anio_contrato', models.IntegerField()),
                ('especialidad', models.CharField(max_length=30)),
                ('area', models.CharField(max_length=30)),
                ('identificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='authApp.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('georreferencia', models.CharField(max_length=45)),
                ('identificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='authApp.persona')),
                ('cedula_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authApp.medico')),
                ('cedula_enfermera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authApp.enfermera')),
                ('cedula_familiar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authApp.familiar')),
            ],
        ),
        migrations.AddField(
            model_name='persona',
            name='codigo_rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authApp.rol'),
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='authApp.paciente')),
                ('codigo', models.PositiveIntegerField()),
                ('en_cuidado', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Sugerencias',
            fields=[
                ('id_codigo', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('diagnostico', models.CharField(max_length=45)),
                ('recomendaciones', models.CharField(max_length=45)),
                ('fecha', models.DateField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authApp.medico')),
                ('historico_cedula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authApp.historico')),
            ],
        ),
        migrations.CreateModel(
            name='SignosVitales',
            fields=[
                ('id_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('oximetria', models.CharField(max_length=45)),
                ('frecuencia_respiratoria', models.CharField(max_length=45)),
                ('frecuencia_cardica', models.CharField(max_length=45)),
                ('temperatura', models.CharField(max_length=45)),
                ('presion_arterial', models.CharField(max_length=45)),
                ('glicemia', models.CharField(max_length=45)),
                ('fecha', models.DateField()),
                ('historico_cedula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authApp.historico')),
            ],
        ),
    ]
