# Generated by Django 4.1.1 on 2022-09-19 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_alter_auxiliar_identificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enfermera',
            name='identificacion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='authApp.persona'),
        ),
        migrations.AlterField(
            model_name='familiar',
            name='identificacion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='authApp.persona'),
        ),
        migrations.AlterField(
            model_name='historico',
            name='paciente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='authApp.paciente'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='identificacion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='authApp.persona'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='identificacion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='authApp.persona'),
        ),
    ]
