from .rol import Rol
from .persona import Persona
from .auxiliar import Auxiliar
from .familiar import Familiar
from .medico import Medico
from .enfermera import Enfermera
from .historico import Historico
from .signos import SignosVitales
from .sugerencias import Sugerencias
from .paciente import Paciente